# Generated by Django 3.0.5 on 2020-04-09 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='syntax',
            field=models.CharField(blank=True, max_length=75, verbose_name='Syntax'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='urn',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='URN'),
        ),
    ]
