# Generated by Django 3.0.5 on 2020-04-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_auto_20200409_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title'),
        ),
    ]
