# Generated by Django 3.0.5 on 2020-04-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_snippet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='source',
            field=models.UUIDField(blank=True, null=True, verbose_name='Source Snippet'),
        ),
    ]
